"""Invoke tasks for srg-core development.

Usage:
    invoke check          # pre-commit hooks (fmt + clippy + knots) + tests — the CI gate
    invoke test           # cargo test
    invoke build          # cargo build (--release optional)
    invoke bump-version   # bump the crate version in Cargo.toml (dry-run with no args)

Install invoke: pip install invoke   (or use the shared venv's copy)
"""

import re
import sys
from pathlib import Path

from invoke import task

SEMVER = r"\d+\.\d+\.\d+"

# The generated parser-parity corpus (Python oracle output); regenerated by
# `invoke conformance`, read by tests/parser_parity.rs. Under target/ so it is
# git-ignored and wiped by `cargo clean`.
CARDS_IR = "target/conformance/cards.ir.json"


def _read_cargo_version() -> str:
    cargo = Path("Cargo.toml").read_text()
    match = re.search(r'^version = "([^"]+)"', cargo, re.MULTILINE)
    if not match:
        raise RuntimeError("could not find package version in Cargo.toml")
    return match.group(1)


@task
def check(c):
    """Run the full gate: pre-commit hooks (fmt + clippy + knots), then tests."""
    c.run("pre-commit run --all-files", pty=True)
    c.run("cargo test", pty=True)


@task
def test(c):
    """Run the test suite."""
    c.run("cargo test", pty=True)


@task
def conformance(c):
    """Cross-language conformance harness vs the Python oracle (substrate-split.md §6).

    The migration's build-time safety rail (transitional — the oracle retires once
    the Rust port is authoritative, so this is *not* part of `invoke check`). It
    drives the Python parity oracle (``~/data/srg_sim_python``; ``$SRG_PY`` to
    override) and checks what is genuinely cross-language:

      * **Parser parity** — regenerate ``cards.ir.json`` from the oracle over the
        whole card DB, then re-parse every record with the Rust parser and assert
        value-identical IR (``tests/parser_parity.rs``).
      * **Snapshot/replay parity** — restore==replay at every decision boundary
        (``tests/session.rs::snapshot_restores_at_every_boundary``, hermetic).

    Whole-log parity is *not* re-checked against the live oracle: the Rust canonical
    RNG is splitmix64 while the ``python`` branch is Mersenne Twister (an accepted
    design split), so log parity is owned by the frozen conformance corpus that Rust
    reproduces byte-for-byte in ``tests/engine_conformance.rs``.
    """
    # sys.executable is the venv interpreter running invoke — it has the oracle's deps.
    c.run(f"{sys.executable} scripts/gen_cards_ir.py {CARDS_IR}", pty=True)
    c.run(
        f"SRG_CARDS_IR={CARDS_IR} cargo test --test parser_parity --test session -- --nocapture",
        pty=True,
    )


@task
def build(c, release=False):
    """Build the crate (debug by default; --release for optimized)."""
    c.run("cargo build --release" if release else "cargo build", pty=True)


@task(name="bump-version")
def bump_version(c, new_version=None):
    """Bump the crate version in Cargo.toml. With no --new-version, prints current."""
    current = _read_cargo_version()
    if not new_version:
        print(f"Current version (Cargo.toml): {current}")
        print("Run: invoke bump-version --new-version X.Y.Z")
        return
    if not re.fullmatch(SEMVER, new_version):
        raise SystemExit(f"--new-version must look like X.Y.Z, got '{new_version}'")
    path = Path("Cargo.toml")
    text = path.read_text()
    updated = re.sub(
        r'^(version = ")' + SEMVER + r'(")',
        rf"\g<1>{new_version}\g<2>",
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if updated == text:
        print("No version string changed.")
        return
    path.write_text(updated)
    print(f"Bumped {current} -> {new_version} in Cargo.toml")
