//! Policy parity (task 73): the golden conformance fixtures were generated by the
//! Python policies (heuristic / aggressive / smart / newbie) playing from a seed.
//! Driving a fresh Rust match with the same-named policies at the same seed must
//! regenerate the fixture's `GameLog` byte-for-byte — proving the ported policies
//! choose exactly as the oracle's do, decision for decision.

use serde_json::Value;
use srg_core::cards::Deck;
use srg_core::engine::Engine;
use srg_core::policy::{build_policy, Policies};
use std::collections::BTreeMap;
use std::path::PathBuf;

struct Fixture {
    label: String,
    deck_a: Deck,
    deck_b: Deck,
    policies: BTreeMap<String, String>,
    seed: u64,
    kind: String,
    log: Vec<Value>,
}

fn fixtures() -> Vec<Fixture> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/conformance");
    let mut out = Vec::new();
    for entry in std::fs::read_dir(&dir).expect("read conformance dir") {
        let path = entry.expect("entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let doc: Value =
            serde_json::from_str(&std::fs::read_to_string(&path).expect("read")).expect("json");
        out.push(Fixture {
            label: path.file_stem().unwrap().to_string_lossy().into_owned(),
            deck_a: serde_json::from_value(doc["decks"]["A"].clone()).expect("deck A"),
            deck_b: serde_json::from_value(doc["decks"]["B"].clone()).expect("deck B"),
            policies: serde_json::from_value(doc["policies"].clone()).expect("policies"),
            seed: doc["seed"].as_u64().expect("seed"),
            kind: doc["kind"].as_str().unwrap_or("sim").to_owned(),
            log: doc["log"].as_array().expect("log array").clone(),
        });
    }
    assert!(!out.is_empty(), "no conformance fixtures");
    out
}

fn assert_log_eq(label: &str, got: &[Value], want: &[Value]) {
    for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
        assert_eq!(
            g,
            w,
            "{label}: log record {i} differs\n  got : {}\n  want: {}",
            serde_json::to_string(g).unwrap(),
            serde_json::to_string(w).unwrap(),
        );
    }
    assert_eq!(
        got.len(),
        want.len(),
        "{label}: log length differs (got {}, want {})",
        got.len(),
        want.len(),
    );
}

/// Each fixture, replayed live: build the named policies for A and B, play from the
/// seed, and assert the produced log matches the fixture byte-for-byte.
#[test]
fn policies_regenerate_fixture_logs() {
    for fx in fixtures() {
        let a = build_policy(&fx.policies["A"])
            .unwrap_or_else(|| panic!("{}: unknown policy A={}", fx.label, fx.policies["A"]));
        let b = build_policy(&fx.policies["B"])
            .unwrap_or_else(|| panic!("{}: unknown policy B={}", fx.label, fx.policies["B"]));
        let decider = Box::new(Policies::new(a, b));
        let mut engine = Engine::new(
            fx.deck_a,
            fx.deck_b,
            decider,
            fx.seed,
            String::new(),
            fx.kind,
        );
        engine
            .play()
            .unwrap_or_else(|_| panic!("{}: live policy play suspended", fx.label));
        assert_log_eq(&fx.label, &engine.log.canonical(), &fx.log);
    }
}
